import Link from "next/link";
import "../styles/globals.css";
import NavBar from "./NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <NavBar />
        <main className=" flex h-[90%] w-full flex-col items-center justify-center">
          {children}
        </main>
      </body>
    </html>
  );
}
